import type { CleanerApplicationResult } from '@/lib/types/application'

export const MOCK_APPLICATIONS: CleanerApplicationResult[] = [
  {
    id: '1',
    full_name: 'Tamar Avraham',
    email: 'tamar.avraham@example.com',
    phone: '054-111-2222',
    bio: 'Experienced residential cleaner, available weekday mornings.',
    service_types: ['residential'],
    hourly_rate: 75,
    years_experience: 4,
    languages: ['HE', 'EN'],
    address: '10 Ben Yehuda St, Tel Aviv',
    status: 'pending',
    submitted_at: '2026-06-10',
    id_document_url: null,
    admin_notes: null,
  },
  {
    id: '2',
    full_name: 'Omar Haddad',
    email: 'omar.haddad@example.com',
    phone: '052-333-4444',
    bio: 'Commercial cleaning specialist for offices and retail spaces.',
    service_types: ['commercial'],
    hourly_rate: 90,
    years_experience: 7,
    languages: ['AR', 'EN', 'HE'],
    address: '5 Hertzel St, Haifa',
    status: 'pending',
    submitted_at: '2026-06-11',
    id_document_url: null,
    admin_notes: null,
  },
  {
    id: '3',
    full_name: 'Irina Volkova',
    email: 'irina.volkova@example.com',
    phone: '050-555-6666',
    bio: 'Detail-oriented cleaner for homes and small offices, flexible schedule.',
    service_types: ['residential', 'commercial'],
    hourly_rate: 80,
    years_experience: 3,
    languages: ['RU', 'HE'],
    address: '22 Allenby St, Tel Aviv',
    status: 'pending',
    submitted_at: '2026-06-12',
    id_document_url: null,
    admin_notes: null,
  },
]
